@startuml

title __SINGLETON's Class Diagram__\n

  package singleton {
    class Singleton {
        {static} - instance : Singleton
        - Singleton()
        {static} + getInstance()
    }
  }

@enduml
